"use strict";
exports.__esModule = true;
var mamiferos_1 = require("./mamiferos");
var herviboros_1 = require("./herviboros");
var carnivoros_1 = require("./carnivoros");
var omnivoros_1 = require("./omnivoros");
var mamifero1 = new mamiferos_1.Mamifero("Gato", 4, true, false);
var herviboro1 = new herviboros_1.Herviboro("Jirafa", 4, true, false, false);
var carnivoro1 = new carnivoros_1.Carnivoro("Leon", 4, true, false, ["Cebra", "Antílopes"], true, true);
var omnivoro1 = new omnivoros_1.Omnivoro("Cerdo", 4, true, false, true, true);
mamifero1.comer();
carnivoro1.comer();
omnivoro1.comer();
herviboro1.comer();
